"""Resources for Markdown files generated by MarkItDown conversion."""

from __future__ import annotations

import asyncio
from pathlib import Path
from urllib.parse import unquote

from mcp.server.fastmcp import FastMCP


def register_markitdown_resources(mcp: FastMCP, output_dir: Path) -> None:
    """Register resource routes for generated Markdown conversion outputs."""

    @mcp.resource("markitdown://{filename}")
    async def get_markitdown_file(filename: str) -> str:
        """Read a generated Markdown file by resource filename."""
        decoded_name = unquote(filename)
        if (
            "/" in decoded_name
            or "\\" in decoded_name
            or ".." in decoded_name
            or decoded_name.startswith(("/", "\\"))
        ):
            raise ValueError("Directory traversal attempt detected.")

        file_path = (output_dir / decoded_name).resolve()
        if not file_path.is_relative_to(output_dir.resolve()):
            raise ValueError("Directory traversal attempt detected.")
        if not file_path.is_file():
            raise FileNotFoundError(f"MarkItDown output not found: {filename}")
        return await asyncio.to_thread(file_path.read_text, encoding="utf-8")
